### ISSUE TITLE
FLUID BUCKET

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#278]
its bacic but yet useful, when you make a new fluid your bucket for the fluid if you made a bucket will show up net to the fluid when trying to make recipes

it would be easy just code it so when the person makes a new fluid an item for that new fluid shows up 

this can be useful for people trying to use there fluids for recipes but cant becuase the bucket dosent count as a item in the page with all your elements

**Comment by Max094Reikeb** [comment]
Please respect the feature request template. Also I advice you to speak a good english, I did not understand everything you wrote...

**Comment by Sajevius** [comment]
He probably meant to say that we should be able to see & select a custom fluid's **bucket item** in the block/item selection window on fields where the user selects a block or item for something (recipes in particular, where MCreator/MCToolkit asks users to select what items/blocks will be used for ingredient or result). 
there are 2 things needed when creating a placeable fluid: **the bucket that places it** (item), and the **actual block for it** (fluid block); he wants the bucket to show up in the selection window too, not just the fluid block, since MCR/MCT **only** shows the fluid block as far as we know. using the block in a recipe ingredient would make recipe almost impossible to craft, since the actual block of the fluid is unobtainable without cheats on; and it just doesn't make sense to use a fluid block instead of the actual bucket.
I personally think this is a good feature request, it would greatly help when people are making recipes using their custom fluid! I just wish it was worded more clearly, but hey, English isn't everyone's first language.

**Comment by tomiscool850** [comment]
excatly what i mean thanks

**Comment by tomiscool850** [comment]
i cant make any fluid recipes and that requires hard coding so i think it would just be a good feature
its also easy
